[2019-04-23 09:14:19,783] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 09:14:39,964] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 09:14:39,986] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 09:14:39,993] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 09:15:31,085] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 09:15:31,105] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 09:15:31,111] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 09:21:52,075] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 09:21:52,095] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 09:21:52,101] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 09:23:31,312] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 09:23:31,332] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 09:23:31,338] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 09:56:20,303] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:12:05,832] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:12:05,845] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:12:05,851] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:12:18,707] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:12:18,720] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:12:18,726] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:13:04,322] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:13:04,336] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:13:04,342] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:13:27,706] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:13:27,717] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:13:27,726] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:14:10,670] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:14:10,684] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:14:10,690] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:16:04,641] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:16:04,654] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:16:04,661] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:16:11,605] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:16:11,618] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:16:11,625] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:16:41,298] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:16:41,311] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:16:41,316] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:16:57,631] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:16:57,644] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:16:57,650] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:17:21,545] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:17:21,559] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:17:21,566] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:18:53,897] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:18:53,910] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:18:53,915] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:20:56,397] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:20:56,408] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:20:56,417] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:23:08,660] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:23:08,674] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:23:08,680] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:23:17,075] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:23:17,089] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:23:17,095] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:24:06,236] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:24:06,250] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:24:06,256] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:24:36,351] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:24:36,365] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:24:36,371] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:25:09,815] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:25:09,826] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:25:09,835] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:25:19,313] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:25:19,328] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:25:19,334] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:25:31,171] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:25:31,184] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:25:31,191] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:28:06,730] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:28:06,743] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:28:06,750] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:29:54,482] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:29:54,494] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:29:54,502] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:37:13,805] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:37:13,818] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:37:13,825] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:37:56,028] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:37:56,040] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:37:56,048] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:38:03,510] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:38:03,523] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:38:03,529] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:39:26,085] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:39:26,098] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:39:26,105] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:41:08,323] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:41:08,338] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:41:08,344] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:41:41,612] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:41:41,625] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:41:41,634] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:41:51,420] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:41:51,433] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:41:51,440] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:44:42,569] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:44:42,585] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:44:42,591] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:46:04,747] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:46:04,760] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:46:04,767] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:46:19,088] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:46:19,104] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:46:19,111] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 10:47:18,796] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 10:47:18,809] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 10:47:18,818] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:33:25,786] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:33:25,786] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:33:25,865] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:33:26,020] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:33:26,068] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:33:26,068] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 11:33:26,137] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 11:33:26,163] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 11:33:31,187] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 11:35:36,006] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:35:36,006] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:35:36,045] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:35:36,168] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:35:36,174] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:35:36,174] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 11:35:36,194] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 11:35:36,196] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 11:35:41,204] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 11:35:58,335] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:35:58,335] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:35:58,372] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:35:58,510] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:35:58,516] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:35:58,516] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 11:35:58,540] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 11:35:58,540] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 11:36:03,549] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 11:37:15,177] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:37:15,190] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:37:15,197] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:38:03,838] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:38:03,838] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:38:03,875] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:38:03,999] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:38:04,003] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:38:04,003] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 11:38:04,025] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 11:38:04,025] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 11:38:09,032] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 11:38:28,940] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:38:28,940] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:38:28,982] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:38:29,118] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:38:29,122] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:38:29,122] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 11:38:29,147] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 11:38:29,148] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 11:38:34,154] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 11:38:50,236] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:38:50,237] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:38:50,276] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:38:50,400] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:38:50,404] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:38:50,404] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 11:38:50,427] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 11:38:50,427] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 11:38:55,434] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 11:40:23,706] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:40:23,707] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:40:23,746] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:40:23,875] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:40:23,880] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:40:23,881] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 11:40:23,901] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 11:40:23,901] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 11:40:28,908] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 11:40:48,326] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:40:48,326] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:40:48,374] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:40:48,519] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:40:48,526] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:40:51,798] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:40:51,799] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:40:51,835] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:40:51,957] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:40:51,963] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:40:51,963] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 11:40:51,986] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 11:40:51,986] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 11:40:56,993] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 11:43:08,701] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:43:08,701] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:43:08,746] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:43:08,881] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:43:08,887] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:43:13,648] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:43:13,648] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:43:13,691] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:43:13,818] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:43:13,822] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:43:13,822] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 11:43:13,845] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 11:43:58,503] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:43:58,503] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:43:58,545] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:43:58,674] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:43:58,678] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:43:58,678] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 11:43:58,700] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 11:44:24,997] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:44:24,999] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:44:25,042] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:44:25,183] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:44:25,187] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:44:25,187] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 11:44:25,210] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 11:44:46,516] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:44:46,516] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:44:46,556] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:44:46,687] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:44:46,693] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:44:46,693] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 11:44:46,714] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 11:44:56,901] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:44:56,901] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:44:56,941] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:44:57,069] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:44:57,073] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:44:57,075] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 11:44:57,098] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 11:46:14,012] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:46:14,012] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:46:14,052] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:46:14,178] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:46:14,184] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:46:14,184] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 11:46:14,206] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 11:46:14,207] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 11:46:19,214] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 11:46:50,236] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:46:50,236] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:46:50,276] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:46:50,404] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:46:50,410] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:46:50,410] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 11:46:50,430] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 11:46:50,431] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 11:46:55,438] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 11:48:06,677] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:48:06,677] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:48:06,717] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:48:06,848] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:48:06,851] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:48:06,852] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 11:48:06,874] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 11:48:06,874] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 11:48:11,881] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 11:49:06,171] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:49:06,171] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:49:06,210] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:49:06,338] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:49:06,344] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:49:06,344] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 11:49:06,367] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 11:49:06,367] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 11:49:11,374] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 11:50:13,595] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:50:13,595] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:50:13,634] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:50:13,772] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:50:13,776] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:50:13,776] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 11:50:13,802] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 11:50:13,803] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 11:50:18,809] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 11:51:16,318] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:51:16,318] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:51:16,358] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:51:16,483] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:51:16,486] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:51:16,487] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 11:51:16,509] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 11:51:16,510] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 11:51:21,516] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 11:52:18,108] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:52:18,108] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:52:18,147] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:52:18,276] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:52:18,280] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:52:18,282] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 11:52:18,303] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 11:52:18,305] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 11:52:23,312] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 11:53:33,227] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:53:33,229] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:53:33,269] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:53:33,392] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:53:33,397] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:53:33,398] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 11:53:33,418] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 11:53:33,418] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 11:53:38,427] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 11:55:41,038] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:55:41,039] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:55:41,078] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:55:41,207] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:55:41,213] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:55:41,213] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 11:55:41,234] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 11:55:41,236] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 11:55:46,243] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 11:57:44,338] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:57:44,338] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:57:44,378] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:57:44,505] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:57:44,509] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:57:44,510] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 11:57:44,532] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 11:57:44,533] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 11:57:49,540] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 11:59:27,405] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 11:59:27,407] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:59:27,444] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 11:59:27,575] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 11:59:27,579] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 11:59:27,581] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 11:59:27,601] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 11:59:27,602] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 11:59:32,608] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 13:32:52,779] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 13:32:52,792] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 13:32:52,799] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 13:34:55,632] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 13:34:55,632] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 13:34:55,671] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 13:34:55,799] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 13:34:55,805] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 13:34:55,805] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 13:34:55,826] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 13:34:55,826] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 13:35:00,835] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 13:35:46,484] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 13:35:46,486] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 13:35:46,528] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 13:35:46,653] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 13:35:46,657] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 13:35:46,657] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 13:35:46,678] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 13:35:46,680] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 13:35:51,687] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 13:35:54,282] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 13:35:59,322] - log_print.py] - ERROR: ----------------返回结果失败----------------：第2个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/riskVerify/zhiMaAuth ]
[2019-04-23 13:36:01,415] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 13:37:06,428] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 13:37:06,430] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 13:37:06,467] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 13:37:06,592] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 13:37:06,596] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 13:37:06,596] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 13:37:06,618] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 13:37:06,618] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 13:37:11,625] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 13:37:55,756] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 13:37:55,756] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 13:37:55,795] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 13:37:55,921] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 13:37:55,927] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 13:37:55,927] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 13:37:55,948] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 13:37:55,948] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 13:38:00,957] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 13:38:46,957] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 13:38:46,957] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 13:38:47,000] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 13:38:47,130] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 13:38:47,134] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 13:38:47,134] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 13:38:47,157] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 13:38:47,157] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 13:38:52,164] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 13:38:54,776] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 13:46:39,438] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 13:46:39,440] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 13:46:39,480] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 13:46:39,615] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 13:46:39,619] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 13:46:39,621] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 13:46:39,644] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 13:46:39,644] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 13:46:44,651] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 13:46:46,891] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 13:46:51,927] - log_print.py] - ERROR: ----------------返回结果失败----------------：第2个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/riskVerify/zhiMaAuth ]
[2019-04-23 13:46:54,000] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 13:46:59,042] - log_print.py] - ERROR: ----------------返回结果失败----------------：第3个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/tjVerify/operatorVerify ]
[2019-04-23 13:47:01,400] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 13:47:01,438] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceErrorCorrect
[2019-04-23 13:47:06,447] - log_print.py] - ERROR: ----------------返回结果失败----------------：第4个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceErrorCorrect ]
[2019-04-23 13:47:08,631] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 13:47:08,667] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/tjVerify/apiVerify
[2019-04-23 14:07:20,234] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 14:07:20,249] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 14:07:20,256] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 14:07:28,575] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 14:07:28,588] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 14:07:28,595] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 14:07:34,140] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 14:07:34,153] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 14:07:34,160] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 14:08:00,332] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 14:08:00,345] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 14:08:00,351] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 14:11:26,841] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 14:11:26,855] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 14:11:26,862] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 14:11:51,516] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 14:11:51,530] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 14:11:51,538] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 14:12:04,624] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 14:12:04,637] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 14:12:04,641] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 14:12:04,642] - log_print.py] - INFO: ----------------查询结束,数据库无数据----------------
[2019-04-23 14:12:42,447] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 14:12:42,460] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 14:12:42,466] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 14:12:49,950] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 14:12:49,961] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 14:12:49,969] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 14:38:51,223] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 14:38:51,234] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 14:38:51,243] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 14:39:17,345] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 14:39:17,358] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 14:39:17,365] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 14:39:51,118] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 14:39:51,131] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 14:39:51,137] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 14:41:33,150] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 14:41:33,163] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 14:41:33,168] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 14:55:14,121] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 14:55:14,121] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 14:55:14,158] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 14:55:14,288] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 14:55:14,292] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 14:55:14,293] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 14:55:14,318] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 14:55:14,318] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 14:55:14,319] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 14:55:14,358] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 14:55:19,365] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 14:55:21,730] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 14:55:26,811] - log_print.py] - ERROR: ----------------返回结果失败----------------：第2个测试用例的接口请求超时响应,请注意!!, [ http://116.62.67.80:9050/riskVerify/zhiMaAuth ]
[2019-04-23 14:55:29,058] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 15:21:41,434] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 15:21:41,434] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 15:21:41,473] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 15:21:41,601] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 15:21:41,605] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 15:21:41,607] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 15:21:41,631] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-23 15:21:41,631] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 15:21:41,632] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 15:21:41,684] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 15:21:41,684] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 15:21:46,691] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 15:21:49,586] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 15:21:49,619] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 15:21:54,665] - log_print.py] - ERROR: ----------------返回结果失败----------------：第2个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/riskVerify/zhiMaAuth ]
[2019-04-23 15:21:56,798] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 15:21:56,832] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 15:22:33,375] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 15:22:33,377] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 15:22:33,414] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 15:22:33,536] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 15:22:33,540] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 15:22:33,540] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 15:22:33,562] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-23 15:22:33,562] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 15:22:33,563] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 15:22:33,598] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 15:22:33,599] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 15:22:38,607] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 15:22:40,941] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 15:22:40,980] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 15:22:46,023] - log_print.py] - ERROR: ----------------返回结果失败----------------：第2个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/riskVerify/zhiMaAuth ]
[2019-04-23 15:22:48,621] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 15:22:48,653] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 15:46:16,049] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 15:46:16,049] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 15:46:16,086] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 15:46:16,207] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 15:46:16,211] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 15:46:16,211] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 15:46:16,233] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-23 15:46:16,233] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 15:46:16,234] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 15:46:16,273] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 15:46:16,275] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 15:46:21,282] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 15:46:21,323] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 15:46:23,677] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 15:46:23,714] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 15:46:28,752] - log_print.py] - ERROR: ----------------返回结果失败----------------：第2个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/riskVerify/zhiMaAuth ]
[2019-04-23 15:46:28,789] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 15:46:30,881] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 15:46:30,911] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 15:46:35,950] - log_print.py] - ERROR: ----------------返回结果失败----------------：第3个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/tjVerify/operatorVerify ]
[2019-04-23 15:46:35,990] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 15:46:38,105] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 15:46:38,137] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 15:46:38,181] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceErrorCorrect
[2019-04-23 15:46:43,186] - log_print.py] - ERROR: ----------------返回结果失败----------------：第4个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceErrorCorrect ]
[2019-04-23 15:46:43,233] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 15:46:45,631] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 15:46:45,660] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 15:46:45,697] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/tjVerify/apiVerify
[2019-04-23 15:46:50,700] - log_print.py] - ERROR: ----------------返回结果失败----------------：第5个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/tjVerify/apiVerify ]
[2019-04-23 15:46:50,740] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 15:46:52,806] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 15:46:52,836] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 15:46:57,877] - log_print.py] - ERROR: ----------------返回结果失败----------------：第6个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/userAmount ]
[2019-04-23 15:46:57,930] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 15:47:00,043] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 15:47:00,072] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 15:47:00,131] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/addContacts
[2019-04-23 15:47:05,134] - log_print.py] - ERROR: ----------------返回结果失败----------------：第7个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/addContacts ]
[2019-04-23 15:47:05,180] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 15:47:07,532] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 15:47:07,568] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 15:47:07,607] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/addSelfContacts
[2019-04-23 15:47:12,617] - log_print.py] - ERROR: ----------------返回结果失败----------------：第8个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/addSelfContacts ]
[2019-04-23 15:47:12,647] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 15:47:14,621] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 15:47:14,651] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 15:50:14,956] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 15:50:14,957] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 15:50:14,964] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 15:59:37,500] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 15:59:37,502] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 15:59:37,509] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 16:02:43,683] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 16:02:43,684] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 16:02:43,690] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 16:03:04,328] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 16:03:04,332] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 16:03:04,338] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 16:03:23,190] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 16:03:23,191] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 16:03:23,197] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 16:04:24,479] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 16:04:24,480] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 16:04:24,487] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 16:05:32,391] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 16:05:32,394] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 16:05:32,400] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 16:17:00,427] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 16:17:00,428] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 16:17:00,434] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 16:19:09,513] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 16:19:09,513] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 16:19:09,555] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 16:19:09,690] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 16:19:09,696] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 16:19:09,697] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 16:19:09,719] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-23 16:19:09,719] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 16:19:09,720] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 16:19:09,805] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 16:19:09,805] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 16:19:14,812] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 16:19:14,881] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 16:19:17,339] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 16:19:17,369] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 16:19:22,420] - log_print.py] - ERROR: ----------------返回结果失败----------------：第2个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/riskVerify/zhiMaAuth ]
[2019-04-23 16:19:22,464] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 16:19:24,733] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 16:19:24,767] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 16:19:29,871] - log_print.py] - ERROR: ----------------返回结果失败----------------：第3个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/tjVerify/operatorVerify ]
[2019-04-23 16:19:29,940] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 16:19:31,947] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 16:19:31,980] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 16:19:32,082] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceErrorCorrect
[2019-04-23 16:19:37,092] - log_print.py] - ERROR: ----------------返回结果失败----------------：第4个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceErrorCorrect ]
[2019-04-23 16:19:37,140] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 16:19:39,335] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 16:19:39,368] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 16:19:39,414] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/tjVerify/apiVerify
[2019-04-23 16:19:44,423] - log_print.py] - ERROR: ----------------返回结果失败----------------：第5个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/tjVerify/apiVerify ]
[2019-04-23 16:19:44,473] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 16:19:46,630] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 16:19:46,667] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 16:19:51,717] - log_print.py] - ERROR: ----------------返回结果失败----------------：第6个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/userAmount ]
[2019-04-23 16:19:51,753] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 16:19:53,819] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 16:19:53,852] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 16:19:53,901] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/addContacts
[2019-04-23 16:19:58,911] - log_print.py] - ERROR: ----------------返回结果失败----------------：第7个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/addContacts ]
[2019-04-23 16:19:58,980] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 16:20:01,170] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 16:20:01,200] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 16:20:01,246] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/addSelfContacts
[2019-04-23 16:20:06,249] - log_print.py] - ERROR: ----------------返回结果失败----------------：第8个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/addSelfContacts ]
[2019-04-23 16:20:06,296] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 16:20:08,522] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 16:20:08,559] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 16:20:08,654] - log_print.py] - INFO: ----------------生成测试报告----------------
[2019-04-23 16:20:08,654] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 16:20:08,657] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 16:20:08,664] - log_print.py] - INFO: ----------------测试用例执行完毕,开始发送测试报告----------------
[2019-04-23 16:20:11,039] - log_print.py] - INFO: ----------------测试报告发送成功----------------
[2019-04-23 16:37:59,223] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 16:37:59,224] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 16:37:59,232] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 16:39:49,795] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 16:39:49,796] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 16:39:49,803] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 16:42:17,517] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 16:42:17,519] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 16:42:17,526] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 16:42:20,529] - log_print.py] - INFO: ----------------查询结束,数据库无数据----------------
[2019-04-23 16:43:08,026] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 16:43:08,028] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 16:43:08,035] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 16:43:20,414] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 16:43:20,417] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 16:43:20,421] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 16:43:51,584] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 16:43:51,585] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 16:43:51,592] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 16:46:53,288] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 16:46:53,289] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 16:46:53,328] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 16:46:53,457] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 16:46:53,461] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 16:46:53,463] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 16:46:53,483] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-23 16:46:53,483] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 16:46:53,486] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 16:46:53,530] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 16:46:53,532] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 16:46:58,539] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 16:46:58,598] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 16:47:00,842] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 16:47:00,872] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 16:47:05,907] - log_print.py] - ERROR: ----------------返回结果失败----------------：第2个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/riskVerify/zhiMaAuth ]
[2019-04-23 16:47:05,964] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 16:47:08,132] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 16:47:08,173] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 16:47:13,239] - log_print.py] - ERROR: ----------------返回结果失败----------------：第3个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/tjVerify/operatorVerify ]
[2019-04-23 16:47:13,289] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 16:47:15,292] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 16:47:15,326] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 16:47:15,398] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceErrorCorrect
[2019-04-23 16:47:20,407] - log_print.py] - ERROR: ----------------返回结果失败----------------：第4个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceErrorCorrect ]
[2019-04-23 16:47:20,456] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 16:47:22,543] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 16:47:22,575] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 16:47:27,622] - log_print.py] - ERROR: ----------------返回结果失败----------------：第5个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/userAmount ]
[2019-04-23 16:47:27,664] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 16:47:29,844] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 16:47:29,878] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 16:47:29,989] - log_print.py] - INFO: ----------------生成测试报告----------------
[2019-04-23 16:47:30,000] - log_print.py] - INFO: ----------------测试用例执行完毕,开始发送测试报告----------------
[2019-04-23 16:47:32,322] - log_print.py] - INFO: ----------------测试报告发送成功----------------
[2019-04-23 17:05:43,720] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 17:05:43,723] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 17:05:43,732] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 17:12:12,010] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 17:12:12,012] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 17:12:12,051] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 17:12:12,180] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 17:12:12,184] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 17:12:12,187] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 17:12:12,207] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-23 17:12:12,207] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 17:12:12,210] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 17:12:12,253] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 17:12:12,253] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 17:12:17,260] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 17:12:17,305] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 17:12:19,637] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 17:12:19,668] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 17:12:19,719] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/riskVerify/zhiMaAuth
[2019-04-23 17:12:24,723] - log_print.py] - ERROR: ----------------返回结果失败----------------：第2个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/riskVerify/zhiMaAuth ]
[2019-04-23 17:12:24,816] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 17:12:26,776] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 17:12:26,809] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 17:12:26,979] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/tjVerify/operatorVerify
[2019-04-23 17:12:31,990] - log_print.py] - ERROR: ----------------返回结果失败----------------：第3个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/tjVerify/operatorVerify ]
[2019-04-23 17:12:32,042] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 17:12:34,109] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 17:12:34,154] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 17:12:34,207] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceErrorCorrect
[2019-04-23 17:12:39,210] - log_print.py] - ERROR: ----------------返回结果失败----------------：第4个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceErrorCorrect ]
[2019-04-23 17:12:39,252] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 17:12:41,503] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 17:12:41,542] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 17:12:41,595] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/userAmount
[2019-04-23 17:12:46,605] - log_print.py] - ERROR: ----------------返回结果失败----------------：第5个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/userAmount ]
[2019-04-23 17:12:46,653] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 17:12:48,694] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 17:12:48,730] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 17:12:48,992] - log_print.py] - INFO: ----------------生成测试报告----------------
[2019-04-23 17:12:49,003] - log_print.py] - INFO: ----------------测试用例执行完毕,开始发送测试报告----------------
[2019-04-23 17:12:51,657] - log_print.py] - INFO: ----------------测试报告发送成功----------------
[2019-04-23 17:23:37,898] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 17:23:37,900] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 17:23:37,901] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 17:23:37,901] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 17:23:49,078] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 17:23:49,078] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 17:23:49,082] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 17:23:56,786] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 17:23:56,786] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 17:23:56,789] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 17:24:02,441] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 17:24:02,441] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 17:25:14,423] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 17:25:14,423] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 17:25:14,423] - log_print.py] - INFO: ----------------读取配置文件2----------------
[2019-04-23 17:25:19,609] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 17:25:19,609] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 17:25:19,611] - log_print.py] - INFO: ----------------读取配置文件2----------------
[2019-04-23 17:26:04,086] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 17:26:04,086] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 17:26:04,088] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 17:26:14,457] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 17:26:59,128] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 17:26:59,128] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 17:26:59,131] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 17:27:32,859] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 17:27:32,861] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 17:27:32,862] - log_print.py] - INFO: ----------------读取配置文件----------------
[2019-04-23 17:29:59,115] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 17:29:59,276] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 17:29:59,282] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 17:29:59,283] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 17:29:59,305] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-23 17:29:59,305] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 17:29:59,306] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 17:29:59,357] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 17:29:59,358] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 17:30:04,364] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 17:30:04,405] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 17:30:06,803] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 17:30:06,838] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 17:30:06,890] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/riskVerify/zhiMaAuth
[2019-04-23 17:32:06,941] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 17:32:07,107] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 17:32:07,111] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 17:32:07,112] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 17:32:07,132] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-23 17:32:07,132] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 17:32:07,134] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 17:32:07,186] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 17:32:07,187] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 17:34:43,815] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 17:34:43,976] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 17:34:43,980] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 17:34:43,982] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 17:34:44,003] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-23 17:34:44,003] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 17:34:44,005] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 17:34:44,063] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 17:34:44,063] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 18:04:18,009] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 18:04:18,174] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 18:04:18,180] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 18:04:18,180] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 18:05:05,318] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 18:05:05,483] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 18:05:05,487] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 18:05:05,487] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 18:05:29,308] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 18:05:29,469] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 18:05:29,473] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 18:05:29,473] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 18:05:29,494] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-23 18:05:29,496] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 18:05:29,496] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 18:05:29,556] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 18:05:29,556] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 18:05:34,563] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 18:05:34,605] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 18:05:36,937] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 18:05:36,970] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 18:05:37,016] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/riskVerify/zhiMaAuth
[2019-04-23 18:05:42,026] - log_print.py] - ERROR: ----------------返回结果失败----------------：第2个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/riskVerify/zhiMaAuth ]
[2019-04-23 18:05:42,073] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 18:05:44,403] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 18:05:44,436] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 18:05:44,474] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/tjVerify/operatorVerify
[2019-04-23 18:05:49,483] - log_print.py] - ERROR: ----------------返回结果失败----------------：第3个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/tjVerify/operatorVerify ]
[2019-04-23 18:05:49,532] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 18:05:51,641] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 18:05:51,674] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 18:05:51,724] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceErrorCorrect
[2019-04-23 18:05:56,737] - log_print.py] - ERROR: ----------------返回结果失败----------------：第4个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceErrorCorrect ]
[2019-04-23 18:05:56,772] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 18:05:58,730] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 18:05:58,763] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 18:05:58,822] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/userAmount
[2019-04-23 18:06:03,828] - log_print.py] - ERROR: ----------------返回结果失败----------------：第5个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/userAmount ]
[2019-04-23 18:06:03,862] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 18:06:05,976] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 18:06:06,009] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 18:06:06,114] - log_print.py] - INFO: ----------------生成测试报告----------------
[2019-04-23 18:06:06,118] - log_print.py] - INFO: ----------------开始发送测试报告----------------
[2019-04-23 18:06:08,575] - log_print.py] - INFO: ----------------测试报告发送成功----------------
[2019-04-23 18:24:37,226] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 18:24:37,392] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 18:24:37,398] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 18:24:37,400] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 18:24:37,421] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-23 18:24:37,421] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 18:24:37,423] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 18:24:37,467] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 18:24:37,467] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 18:24:42,474] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 18:24:42,516] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 18:24:45,003] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 18:24:45,033] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 18:24:45,089] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/riskVerify/zhiMaAuth
[2019-04-23 18:24:50,096] - log_print.py] - ERROR: ----------------返回结果失败----------------：第2个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/riskVerify/zhiMaAuth ]
[2019-04-23 18:24:50,150] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 18:24:52,415] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 18:24:52,456] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 18:24:52,493] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/tjVerify/operatorVerify
[2019-04-23 18:24:57,502] - log_print.py] - ERROR: ----------------返回结果失败----------------：第3个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/tjVerify/operatorVerify ]
[2019-04-23 18:24:57,551] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 18:24:59,532] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 18:24:59,563] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 18:24:59,607] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceErrorCorrect
[2019-04-23 18:25:04,609] - log_print.py] - ERROR: ----------------返回结果失败----------------：第4个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceErrorCorrect ]
[2019-04-23 18:25:04,642] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 18:25:06,700] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 18:25:06,743] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 18:25:06,790] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/userAmount
[2019-04-23 18:25:11,793] - log_print.py] - ERROR: ----------------返回结果失败----------------：第5个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/userAmount ]
[2019-04-23 18:25:11,839] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 18:25:13,950] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 18:25:13,990] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 18:25:14,089] - log_print.py] - INFO: ----------------生成测试报告----------------
[2019-04-23 18:25:14,095] - log_print.py] - INFO: ----------------开始发送测试报告----------------
[2019-04-23 18:25:16,453] - log_print.py] - INFO: ----------------测试报告发送成功----------------
[2019-04-23 18:26:54,901] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 18:26:55,066] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 18:26:55,072] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 18:26:55,072] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 18:26:55,094] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-23 18:26:55,095] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 18:26:55,096] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 18:26:55,137] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 18:26:55,137] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 18:27:00,144] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 18:27:00,177] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 18:27:02,483] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 18:27:02,515] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 18:27:02,562] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/riskVerify/zhiMaAuth
[2019-04-23 18:27:07,568] - log_print.py] - ERROR: ----------------返回结果失败----------------：第2个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/riskVerify/zhiMaAuth ]
[2019-04-23 18:27:07,611] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 18:27:09,635] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 18:27:09,667] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 18:27:09,710] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/tjVerify/operatorVerify
[2019-04-23 18:27:14,714] - log_print.py] - ERROR: ----------------返回结果失败----------------：第3个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/tjVerify/operatorVerify ]
[2019-04-23 18:27:14,834] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 18:27:17,013] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 18:27:17,049] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 18:27:17,101] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceErrorCorrect
[2019-04-23 18:27:22,104] - log_print.py] - ERROR: ----------------返回结果失败----------------：第4个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceErrorCorrect ]
[2019-04-23 18:27:22,153] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 18:27:24,171] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 18:27:24,201] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 18:27:24,236] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/userAmount
[2019-04-23 18:27:29,240] - log_print.py] - ERROR: ----------------返回结果失败----------------：第5个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/userAmount ]
[2019-04-23 18:27:29,286] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 18:27:31,292] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 18:27:31,328] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 18:27:31,436] - log_print.py] - INFO: ----------------生成测试报告----------------
[2019-04-23 18:27:31,447] - log_print.py] - INFO: ----------------开始发送测试报告----------------
[2019-04-23 18:27:33,723] - log_print.py] - INFO: ----------------测试报告发送成功----------------
[2019-04-23 18:29:26,082] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-23 18:29:26,249] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 18:29:26,255] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 18:29:26,256] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-23 18:29:26,276] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-23 18:29:26,276] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-23 18:29:26,279] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-23 18:29:26,322] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-23 18:29:26,322] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-23 18:29:31,329] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-23 18:29:31,398] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 18:29:33,713] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 18:29:33,747] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 18:29:33,798] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/riskVerify/zhiMaAuth
[2019-04-23 18:29:38,802] - log_print.py] - ERROR: ----------------返回结果失败----------------：第2个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/riskVerify/zhiMaAuth ]
[2019-04-23 18:29:38,855] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 18:29:41,165] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 18:29:41,206] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 18:29:41,249] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/tjVerify/operatorVerify
[2019-04-23 18:29:46,259] - log_print.py] - ERROR: ----------------返回结果失败----------------：第3个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/tjVerify/operatorVerify ]
[2019-04-23 18:29:46,306] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 18:29:48,390] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 18:29:48,427] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 18:29:48,463] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceErrorCorrect
[2019-04-23 18:29:53,470] - log_print.py] - ERROR: ----------------返回结果失败----------------：第4个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceErrorCorrect ]
[2019-04-23 18:29:53,523] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 18:29:55,674] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 18:29:55,707] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 18:29:55,763] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/userAmount
[2019-04-23 18:30:00,766] - log_print.py] - ERROR: ----------------返回结果失败----------------：第5个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/userAmount ]
[2019-04-23 18:30:00,812] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-23 18:30:03,036] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-23 18:30:03,071] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-23 18:30:03,256] - log_print.py] - INFO: ----------------生成测试报告----------------
[2019-04-23 18:30:03,275] - log_print.py] - INFO: ----------------开始发送测试报告----------------
[2019-04-23 18:30:05,630] - log_print.py] - INFO: ----------------测试报告发送成功----------------
