[2019-04-24 17:12:56,250] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-24 17:12:56,424] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-24 17:12:56,428] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-24 17:12:56,428] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-24 17:12:56,450] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-24 17:12:56,450] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-24 17:12:56,451] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-24 17:12:56,519] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-24 17:12:56,519] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-24 17:13:01,528] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-24 17:13:01,614] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-24 17:13:04,326] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-24 17:13:04,364] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-24 17:13:04,410] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/riskVerify/zhiMaAuth
[2019-04-24 17:13:09,414] - log_print.py] - ERROR: ----------------返回结果失败----------------：第2个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/riskVerify/zhiMaAuth ]
[2019-04-24 17:13:09,460] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-24 17:13:11,605] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-24 17:13:11,638] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-24 17:13:11,677] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/tjVerify/operatorVerify
[2019-04-24 17:13:16,684] - log_print.py] - ERROR: ----------------返回结果失败----------------：第3个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/tjVerify/operatorVerify ]
[2019-04-24 17:13:16,734] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-24 17:13:18,944] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-24 17:13:18,983] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-24 17:13:19,026] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceErrorCorrect
[2019-04-24 17:13:24,032] - log_print.py] - ERROR: ----------------返回结果失败----------------：第4个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceErrorCorrect ]
[2019-04-24 17:13:24,076] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-24 17:13:26,184] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-24 17:13:26,219] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-24 17:13:26,260] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/userAmount
[2019-04-24 17:13:31,266] - log_print.py] - ERROR: ----------------返回结果失败----------------：第5个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/userAmount ]
[2019-04-24 17:13:31,305] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-24 17:13:33,494] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-24 17:13:33,536] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-24 17:13:33,773] - log_print.py] - INFO: ----------------生成测试报告----------------
[2019-04-24 17:13:33,779] - log_print.py] - INFO: ----------------开始发送测试报告----------------
[2019-04-24 17:13:36,059] - log_print.py] - INFO: ----------------测试报告发送成功----------------
