[2019-04-25 15:58:43,065] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-25 15:58:43,232] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 15:58:43,237] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 15:58:43,237] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-25 15:58:43,259] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-25 15:58:43,260] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 15:58:43,263] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 15:58:43,345] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-25 15:58:43,346] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-25 15:58:48,355] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-25 15:58:48,404] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 15:58:50,719] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 15:58:50,749] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 15:58:50,790] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/riskVerify/zhiMaAuth
[2019-04-25 15:58:55,798] - log_print.py] - ERROR: ----------------返回结果失败----------------：第2个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/riskVerify/zhiMaAuth ]
[2019-04-25 15:58:55,836] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 15:58:58,079] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 15:58:58,109] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 15:58:58,148] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/tjVerify/operatorVerify
[2019-04-25 15:59:03,155] - log_print.py] - ERROR: ----------------返回结果失败----------------：第3个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/tjVerify/operatorVerify ]
[2019-04-25 15:59:03,197] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 15:59:05,448] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 15:59:05,482] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 15:59:05,522] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceErrorCorrect
[2019-04-25 15:59:10,530] - log_print.py] - ERROR: ----------------返回结果失败----------------：第4个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceErrorCorrect ]
[2019-04-25 15:59:10,579] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 15:59:13,183] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 15:59:13,216] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 15:59:13,256] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/userAmount
[2019-04-25 15:59:18,263] - log_print.py] - ERROR: ----------------返回结果失败----------------：第5个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/userAmount ]
[2019-04-25 15:59:18,303] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 15:59:20,344] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 15:59:20,375] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 15:59:20,469] - log_print.py] - INFO: ----------------生成测试报告----------------
[2019-04-25 16:00:30,229] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-25 16:00:30,394] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 16:00:30,398] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 16:00:30,400] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-25 16:00:30,420] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-25 16:00:30,421] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 16:00:30,423] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 16:00:30,470] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-25 16:00:30,470] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-25 16:00:35,476] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-25 16:00:35,526] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 16:00:37,982] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 16:00:38,016] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 16:00:38,096] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/riskVerify/zhiMaAuth
[2019-04-25 16:00:43,104] - log_print.py] - ERROR: ----------------返回结果失败----------------：第2个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/riskVerify/zhiMaAuth ]
[2019-04-25 16:00:43,141] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 16:00:45,585] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 16:00:45,621] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 16:00:45,683] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/tjVerify/operatorVerify
[2019-04-25 16:00:50,687] - log_print.py] - ERROR: ----------------返回结果失败----------------：第3个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/tjVerify/operatorVerify ]
[2019-04-25 16:00:50,727] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 16:00:53,286] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 16:00:53,326] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 16:00:53,371] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceErrorCorrect
[2019-04-25 16:00:58,378] - log_print.py] - ERROR: ----------------返回结果失败----------------：第4个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceErrorCorrect ]
[2019-04-25 16:00:58,417] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 16:01:00,519] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 16:01:00,553] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 16:01:00,592] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/userAmount
[2019-04-25 16:01:05,601] - log_print.py] - ERROR: ----------------返回结果失败----------------：第5个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/userAmount ]
[2019-04-25 16:01:05,642] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 16:01:08,200] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 16:01:08,234] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 16:01:08,328] - log_print.py] - INFO: ----------------生成测试报告----------------
[2019-04-25 16:01:08,339] - log_print.py] - INFO: ----------------开始发送测试报告----------------
[2019-04-25 16:01:10,719] - log_print.py] - INFO: ----------------测试报告发送成功----------------
[2019-04-25 16:02:16,882] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-25 16:02:17,089] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 16:02:17,098] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 16:02:17,098] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-25 16:02:17,124] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-25 16:02:17,125] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 16:02:17,127] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 16:02:17,174] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-25 16:02:17,174] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-25 16:02:22,183] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-25 16:02:22,230] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 16:02:24,753] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 16:02:24,788] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 16:02:24,825] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/riskVerify/zhiMaAuth
[2019-04-25 16:02:29,835] - log_print.py] - ERROR: ----------------返回结果失败----------------：第2个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/riskVerify/zhiMaAuth ]
[2019-04-25 16:02:29,874] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 16:02:31,890] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 16:02:31,926] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 16:02:31,964] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/tjVerify/operatorVerify
[2019-04-25 16:02:36,970] - log_print.py] - ERROR: ----------------返回结果失败----------------：第3个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/tjVerify/operatorVerify ]
[2019-04-25 16:02:37,013] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 16:02:39,801] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 16:02:39,838] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 16:02:39,888] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceErrorCorrect
[2019-04-25 16:02:44,898] - log_print.py] - ERROR: ----------------返回结果失败----------------：第4个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceErrorCorrect ]
[2019-04-25 16:02:45,013] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 16:02:49,115] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 16:02:49,148] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 16:02:49,188] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/userAmount
[2019-04-25 16:02:54,194] - log_print.py] - ERROR: ----------------返回结果失败----------------：第5个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/userAmount ]
[2019-04-25 16:02:54,237] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 16:02:56,447] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 16:02:56,479] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 16:02:56,622] - log_print.py] - INFO: ----------------生成测试报告----------------
[2019-04-25 16:02:56,628] - log_print.py] - INFO: ----------------开始发送测试报告----------------
[2019-04-25 16:02:58,960] - log_print.py] - INFO: ----------------测试报告发送成功----------------
[2019-04-25 16:21:12,177] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-25 16:21:12,345] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 16:21:12,351] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 16:21:12,351] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-25 16:21:12,374] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-25 16:21:12,374] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 16:21:12,375] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 16:21:12,424] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-25 16:21:12,424] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-25 16:21:17,433] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-25 16:21:17,474] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 16:21:19,877] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 16:21:19,908] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 16:21:19,992] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/riskVerify/zhiMaAuth
[2019-04-25 16:21:25,022] - log_print.py] - ERROR: ----------------返回结果失败----------------：第2个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/riskVerify/zhiMaAuth ]
[2019-04-25 16:21:25,059] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 16:21:27,279] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 16:21:27,313] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 16:21:27,381] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/tjVerify/operatorVerify
[2019-04-25 16:21:32,384] - log_print.py] - ERROR: ----------------返回结果失败----------------：第3个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/tjVerify/operatorVerify ]
[2019-04-25 16:21:32,434] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 16:21:34,821] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 16:21:34,858] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 16:21:34,917] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceErrorCorrect
[2019-04-25 16:21:39,924] - log_print.py] - ERROR: ----------------返回结果失败----------------：第4个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceErrorCorrect ]
[2019-04-25 16:21:39,973] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 16:21:42,586] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 16:21:42,618] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 16:21:42,668] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/userAmount
[2019-04-25 16:21:47,678] - log_print.py] - ERROR: ----------------返回结果失败----------------：第5个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/userAmount ]
[2019-04-25 16:21:47,743] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 16:21:50,035] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 16:21:50,066] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 16:21:50,157] - log_print.py] - INFO: ----------------生成测试报告----------------
[2019-04-25 16:21:50,164] - log_print.py] - INFO: ----------------开始发送测试报告----------------
[2019-04-25 16:21:52,569] - log_print.py] - INFO: ----------------测试报告发送成功----------------
[2019-04-25 17:46:39,572] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-25 17:46:39,736] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 17:46:39,742] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 17:46:39,742] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-25 17:46:39,763] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-25 17:46:39,763] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 17:46:39,765] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 17:46:39,805] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-25 17:46:39,805] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-25 17:46:44,812] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-25 17:46:44,862] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 17:46:47,190] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 17:46:47,229] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 17:46:47,265] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/riskVerify/zhiMaAuth
[2019-04-25 17:46:52,273] - log_print.py] - ERROR: ----------------返回结果失败----------------：第2个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/riskVerify/zhiMaAuth ]
[2019-04-25 17:46:52,321] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 17:46:54,417] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 17:46:54,450] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 17:46:54,497] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/tjVerify/operatorVerify
[2019-04-25 17:46:59,505] - log_print.py] - ERROR: ----------------返回结果失败----------------：第3个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/tjVerify/operatorVerify ]
[2019-04-25 17:46:59,546] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 17:47:01,490] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 17:47:01,523] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 17:47:01,561] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceErrorCorrect
[2019-04-25 17:47:06,568] - log_print.py] - ERROR: ----------------返回结果失败----------------：第4个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceErrorCorrect ]
[2019-04-25 17:47:06,614] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 17:47:08,558] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 17:47:08,589] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 17:47:08,647] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/userAmount
[2019-04-25 17:47:13,653] - log_print.py] - ERROR: ----------------返回结果失败----------------：第5个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/userAmount ]
[2019-04-25 17:47:13,704] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 17:47:15,778] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 17:47:15,809] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 17:47:15,897] - log_print.py] - INFO: ----------------生成测试报告----------------
[2019-04-25 17:47:15,911] - log_print.py] - INFO: ----------------开始发送测试报告----------------
[2019-04-25 17:47:18,184] - log_print.py] - INFO: ----------------测试报告发送成功----------------
[2019-04-25 17:48:08,381] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-25 17:48:08,552] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 17:48:08,558] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 17:48:08,558] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-25 17:48:08,578] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-25 17:48:08,578] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 17:48:08,582] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 17:48:08,627] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-25 17:48:08,628] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-25 17:48:13,634] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-25 17:48:13,677] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 17:48:15,934] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 17:48:15,967] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 17:48:16,012] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/riskVerify/zhiMaAuth
[2019-04-25 17:48:21,017] - log_print.py] - ERROR: ----------------返回结果失败----------------：第2个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/riskVerify/zhiMaAuth ]
[2019-04-25 17:48:21,058] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 17:48:22,971] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 17:48:23,003] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 17:48:23,035] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/tjVerify/operatorVerify
[2019-04-25 17:48:28,038] - log_print.py] - ERROR: ----------------返回结果失败----------------：第3个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/tjVerify/operatorVerify ]
[2019-04-25 17:48:28,085] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 17:48:30,211] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 17:48:30,247] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 17:48:30,292] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceErrorCorrect
[2019-04-25 17:48:35,296] - log_print.py] - ERROR: ----------------返回结果失败----------------：第4个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceErrorCorrect ]
[2019-04-25 17:48:35,335] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 17:48:37,476] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 17:48:37,509] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 17:48:37,558] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/userAmount
[2019-04-25 17:48:42,563] - log_print.py] - ERROR: ----------------返回结果失败----------------：第5个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/userAmount ]
[2019-04-25 17:48:42,624] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 17:48:46,114] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 17:48:46,151] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 17:48:46,243] - log_print.py] - INFO: ----------------生成测试报告----------------
[2019-04-25 17:48:46,250] - log_print.py] - INFO: ----------------开始发送测试报告----------------
[2019-04-25 17:48:49,267] - log_print.py] - INFO: ----------------测试报告发送成功----------------
[2019-04-25 17:54:09,477] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-25 17:54:09,651] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 17:54:09,655] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 17:54:09,657] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-25 17:54:09,677] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-25 17:54:09,678] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 17:54:09,680] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 17:54:09,732] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-25 17:54:09,733] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-25 17:54:14,740] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-25 17:54:14,780] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 17:54:17,107] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 17:54:17,138] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 17:54:17,181] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/riskVerify/zhiMaAuth
[2019-04-25 17:54:22,188] - log_print.py] - ERROR: ----------------返回结果失败----------------：第2个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/riskVerify/zhiMaAuth ]
[2019-04-25 17:54:22,230] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 17:54:24,292] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 17:54:24,322] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 17:54:24,355] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/tjVerify/operatorVerify
[2019-04-25 17:54:29,361] - log_print.py] - ERROR: ----------------返回结果失败----------------：第3个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/tjVerify/operatorVerify ]
[2019-04-25 17:54:29,405] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 17:54:31,507] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 17:54:31,539] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 17:54:31,588] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceErrorCorrect
[2019-04-25 17:54:36,598] - log_print.py] - ERROR: ----------------返回结果失败----------------：第4个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceErrorCorrect ]
[2019-04-25 17:54:36,638] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 17:54:38,858] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 17:54:38,930] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 17:54:38,982] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/userAmount
[2019-04-25 17:54:43,986] - log_print.py] - ERROR: ----------------返回结果失败----------------：第5个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/userAmount ]
[2019-04-25 17:54:44,019] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 17:54:46,088] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 17:54:46,119] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 17:54:46,203] - log_print.py] - INFO: ----------------生成测试报告----------------
[2019-04-25 17:54:46,210] - log_print.py] - INFO: ----------------开始发送测试报告----------------
[2019-04-25 17:54:48,448] - log_print.py] - INFO: ----------------测试报告发送成功----------------
[2019-04-25 17:57:44,559] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-25 17:57:44,730] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 17:57:44,736] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 17:57:44,736] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-25 17:57:44,759] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-25 17:57:44,759] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 17:57:44,762] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 17:57:44,808] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-25 17:57:44,809] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-25 17:57:49,816] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-25 17:57:49,855] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 17:57:52,278] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 17:57:52,311] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 17:57:52,348] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/riskVerify/zhiMaAuth
[2019-04-25 17:57:57,355] - log_print.py] - ERROR: ----------------返回结果失败----------------：第2个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/riskVerify/zhiMaAuth ]
[2019-04-25 17:57:57,397] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 17:57:59,884] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 17:57:59,914] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 17:57:59,963] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/tjVerify/operatorVerify
[2019-04-25 17:58:04,969] - log_print.py] - ERROR: ----------------返回结果失败----------------：第3个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/tjVerify/operatorVerify ]
[2019-04-25 17:58:05,013] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 17:58:07,315] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 17:58:07,355] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 17:58:07,391] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceErrorCorrect
[2019-04-25 17:58:12,401] - log_print.py] - ERROR: ----------------返回结果失败----------------：第4个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceErrorCorrect ]
[2019-04-25 17:58:12,448] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 17:58:14,321] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 17:58:14,352] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 17:58:14,388] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/userAmount
[2019-04-25 17:58:19,397] - log_print.py] - ERROR: ----------------返回结果失败----------------：第5个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/userAmount ]
[2019-04-25 17:58:19,447] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 17:58:21,565] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 17:58:21,598] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 17:58:21,714] - log_print.py] - INFO: ----------------生成测试报告----------------
[2019-04-25 17:58:21,726] - log_print.py] - INFO: ----------------开始发送测试报告----------------
[2019-04-25 17:58:24,046] - log_print.py] - INFO: ----------------测试报告发送成功----------------
[2019-04-25 18:05:49,388] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-25 18:05:49,559] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 18:05:49,563] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 18:05:49,565] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-25 18:05:49,585] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-25 18:05:49,586] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 18:05:49,588] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 18:05:49,631] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-25 18:05:49,632] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-25 18:05:54,641] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-25 18:05:54,690] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 18:05:57,132] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 18:05:57,163] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 18:05:57,197] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/riskVerify/zhiMaAuth
[2019-04-25 18:06:02,200] - log_print.py] - ERROR: ----------------返回结果失败----------------：第2个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/riskVerify/zhiMaAuth ]
[2019-04-25 18:06:02,247] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 18:06:04,302] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 18:06:04,334] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 18:06:04,365] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/tjVerify/operatorVerify
[2019-04-25 18:06:09,369] - log_print.py] - ERROR: ----------------返回结果失败----------------：第3个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/tjVerify/operatorVerify ]
[2019-04-25 18:06:09,407] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 18:06:11,582] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 18:06:11,618] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 18:06:11,657] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceErrorCorrect
[2019-04-25 18:06:16,661] - log_print.py] - ERROR: ----------------返回结果失败----------------：第4个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceErrorCorrect ]
[2019-04-25 18:06:16,714] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 18:06:18,836] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 18:06:18,869] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 18:06:18,907] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/userAmount
[2019-04-25 18:06:23,911] - log_print.py] - ERROR: ----------------返回结果失败----------------：第5个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/userAmount ]
[2019-04-25 18:06:23,957] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 18:06:26,102] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 18:06:26,135] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 18:06:26,223] - log_print.py] - INFO: ----------------生成测试报告----------------
[2019-04-25 18:06:26,230] - log_print.py] - INFO: ----------------开始发送测试报告----------------
[2019-04-25 18:06:28,529] - log_print.py] - INFO: ----------------测试报告发送成功----------------
[2019-04-25 18:08:33,868] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-25 18:08:34,039] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 18:08:34,043] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 18:08:34,045] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-25 18:08:34,069] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-25 18:08:34,069] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 18:08:34,072] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 18:08:34,118] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-25 18:08:34,118] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-25 18:10:17,990] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-25 18:10:18,154] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 18:10:18,160] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 18:10:18,160] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-25 18:10:18,181] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-25 18:10:18,181] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 18:10:18,184] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 18:10:18,223] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-25 18:10:18,223] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-25 18:10:57,920] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-25 18:10:58,088] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 18:10:58,092] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 18:10:58,094] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-25 18:10:58,117] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-25 18:10:58,117] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 18:10:58,118] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 18:10:58,163] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-25 18:10:58,164] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-25 18:17:03,907] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-25 18:17:04,073] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 18:17:04,079] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 18:17:04,079] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-25 18:17:04,102] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-25 18:17:04,104] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 18:17:04,105] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 18:17:04,150] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-25 18:17:04,151] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceAuthentication
[2019-04-25 18:17:09,158] - log_print.py] - ERROR: ----------------返回结果失败----------------：第1个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceAuthentication ]
[2019-04-25 18:17:09,221] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 18:17:11,694] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 18:17:11,732] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 18:17:11,776] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/riskVerify/zhiMaAuth
[2019-04-25 18:17:16,782] - log_print.py] - ERROR: ----------------返回结果失败----------------：第2个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/riskVerify/zhiMaAuth ]
[2019-04-25 18:17:16,825] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 18:17:18,855] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 18:17:18,887] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 18:17:18,933] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/tjVerify/operatorVerify
[2019-04-25 18:17:23,936] - log_print.py] - ERROR: ----------------返回结果失败----------------：第3个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/tjVerify/operatorVerify ]
[2019-04-25 18:17:23,983] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 18:17:26,075] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 18:17:26,108] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 18:17:26,186] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/faceErrorCorrect
[2019-04-25 18:17:31,190] - log_print.py] - ERROR: ----------------返回结果失败----------------：第4个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/faceErrorCorrect ]
[2019-04-25 18:17:31,250] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 18:17:33,155] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 18:17:33,190] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 18:17:33,256] - log_print.py] - INFO: ----------------开始调用接口----------------：http://116.62.67.80:9050/baseVerify/userAmount
[2019-04-25 18:17:38,259] - log_print.py] - ERROR: ----------------返回结果失败----------------：第5个测试用例的接口请求超时响应,请注意!! [ http://116.62.67.80:9050/baseVerify/userAmount ]
[2019-04-25 18:17:38,305] - log_print.py] - INFO: ----------------接口超时,开始发送邮件----------------
[2019-04-25 18:17:40,592] - log_print.py] - INFO: ----------------超时邮件发送成功----------------
[2019-04-25 18:17:40,628] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 18:17:40,665] - log_print.py] - INFO: ----------------开始调用接口----------------：http://httpbin.org/get
[2019-04-25 18:21:45,003] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-25 18:21:45,171] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 18:21:45,177] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 18:21:45,177] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-25 18:21:45,197] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-25 18:21:45,197] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 18:21:45,198] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 18:21:45,249] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-25 18:21:45,250] - log_print.py] - INFO: ----------------开始调用接口----------------：http://httpbin.org/get
[2019-04-25 18:24:39,375] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-25 18:24:39,553] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 18:24:39,559] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 18:24:39,559] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-25 18:24:39,579] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-25 18:24:39,581] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 18:24:39,584] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 18:24:39,625] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-25 18:24:39,627] - log_print.py] - INFO: ----------------开始调用接口----------------：http://httpbin.org/get
[2019-04-25 18:27:26,517] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-25 18:27:26,691] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 18:27:26,697] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 18:27:26,697] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-25 18:27:26,719] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-25 18:27:26,720] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 18:27:26,720] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 18:27:26,769] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-25 18:27:26,770] - log_print.py] - INFO: ----------------开始调用接口----------------：http://httpbin.org/get
[2019-04-25 18:28:08,421] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-25 18:28:08,595] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 18:28:08,601] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 18:28:08,601] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-25 18:28:08,621] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-25 18:28:08,621] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 18:28:08,624] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 18:28:08,668] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-25 18:28:08,670] - log_print.py] - INFO: ----------------开始调用接口----------------：http://httpbin.org/get
[2019-04-25 18:28:26,986] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-25 18:28:27,158] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 18:28:27,163] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 18:28:27,164] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-25 18:28:27,184] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-25 18:28:27,186] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 18:28:27,187] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 18:28:27,243] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-25 18:28:27,243] - log_print.py] - INFO: ----------------开始调用接口----------------：http://httpbin.org/get
[2019-04-25 18:29:39,898] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-25 18:29:40,069] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 18:29:40,073] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 18:29:40,075] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-25 18:29:40,095] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-25 18:29:40,095] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 18:29:40,098] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 18:29:40,141] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-25 18:29:40,141] - log_print.py] - INFO: ----------------开始调用接口----------------：http://httpbin.org/get
[2019-04-25 18:29:40,673] - log_print.py] - INFO: ----------------返回结果成功----------------：{
  "args": {
    "{\"name\": \"hongnaiwu\", \"age\": \"26\"}": ""
  }, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate", 
    "Host": "httpbin.org", 
    "User-Agent": "python-requests/2.21.0"
  }, 
  "origin": "115.194.104.2, 115.194.104.2", 
  "url": "https://httpbin.org/get?{\"name\": \"hongnaiwu\", \"age\": \"26\"}"
}

[2019-04-25 18:29:40,673] - log_print.py] - INFO: ----------------测试断言结果----------------：第1个测试用例断言：失败
[2019-04-25 18:29:40,707] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 18:29:40,775] - log_print.py] - INFO: ----------------生成测试报告----------------
[2019-04-25 18:29:40,788] - log_print.py] - INFO: ----------------查询结束,数据库无数据----------------
[2019-04-25 18:31:12,038] - log_print.py] - INFO: ----------------读取配置文件中邮箱信息----------------
[2019-04-25 18:31:12,203] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 18:31:12,209] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 18:31:12,210] - log_print.py] - INFO: ----------------开始读取excel中的测试用例----------------
[2019-04-25 18:31:12,230] - log_print.py] - INFO: ----------------执行用例前插入准备更新的表记录----------------
[2019-04-25 18:31:12,230] - log_print.py] - INFO: ----------------正在连接mysql服务器----------------
[2019-04-25 18:31:12,233] - log_print.py] - INFO: ----------------连接服务器成功----------------
[2019-04-25 18:31:12,269] - log_print.py] - INFO: ----------------开始执行测试用例----------------
[2019-04-25 18:31:12,270] - log_print.py] - INFO: ----------------开始调用接口----------------：http://httpbin.org/get
[2019-04-25 18:31:12,783] - log_print.py] - INFO: ----------------返回结果成功----------------：{
  "args": {
    "{\"name\": \"hongnaiwu\", \"age\": \"26\"}": ""
  }, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate", 
    "Host": "httpbin.org", 
    "User-Agent": "python-requests/2.21.0"
  }, 
  "origin": "115.194.104.2, 115.194.104.2", 
  "url": "https://httpbin.org/get?{\"name\": \"hongnaiwu\", \"age\": \"26\"}"
}

[2019-04-25 18:31:12,785] - log_print.py] - INFO: ----------------测试断言结果----------------：第1个测试用例断言：失败
[2019-04-25 18:31:12,828] - log_print.py] - INFO: ----------------根据用例执行情况,开始更新测试结果表的相关数据----------------
[2019-04-25 18:31:12,881] - log_print.py] - INFO: ----------------生成测试报告----------------
[2019-04-25 18:31:12,887] - log_print.py] - INFO: ----------------查询结束,数据库无数据----------------
